# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClientMenuWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClientMenu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(686, 900)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-image: url(:/Images/DesignBgr.png);")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(150, 160, 391, 451))
        self.widget.setStyleSheet("border-radius:50px;\n"
"border-image: url(:/Images/Beige1.png);")
        self.widget.setObjectName("widget")
        self.labelMenu = QtWidgets.QLabel(self.widget)
        self.labelMenu.setGeometry(QtCore.QRect(110, 10, 161, 51))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(20)
        self.labelMenu.setFont(font)
        self.labelMenu.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMenu.setObjectName("labelMenu")
        self.pushButtonAddOpinion = QtWidgets.QPushButton(self.widget)
        self.pushButtonAddOpinion.setGeometry(QtCore.QRect(50, 110, 271, 31))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(12)
        self.pushButtonAddOpinion.setFont(font)
        self.pushButtonAddOpinion.setStyleSheet("border-image: url(:/Images/Beige2.png);\n"
"border-radius:10px;")
        self.pushButtonAddOpinion.setObjectName("pushButtonAddOpinion")
        self.pushButtonViewOpinion = QtWidgets.QPushButton(self.widget)
        self.pushButtonViewOpinion.setGeometry(QtCore.QRect(50, 170, 271, 31))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(12)
        self.pushButtonViewOpinion.setFont(font)
        self.pushButtonViewOpinion.setStyleSheet("border-image: url(:/Images/Beige2.png);\n"
"border-radius:10px;")
        self.pushButtonViewOpinion.setObjectName("pushButtonViewOpinion")
        self.pushButtonViewRestaurants = QtWidgets.QPushButton(self.widget)
        self.pushButtonViewRestaurants.setGeometry(QtCore.QRect(50, 230, 271, 31))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(12)
        self.pushButtonViewRestaurants.setFont(font)
        self.pushButtonViewRestaurants.setStyleSheet("border-image: url(:/Images/Beige2.png);\n"
"border-radius:10px;")
        self.pushButtonViewRestaurants.setObjectName("pushButtonViewRestaurants")
        self.pushButtonOther = QtWidgets.QPushButton(self.widget)
        self.pushButtonOther.setGeometry(QtCore.QRect(50, 350, 271, 31))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(12)
        self.pushButtonOther.setFont(font)
        self.pushButtonOther.setStyleSheet("border-image: url(:/Images/Beige2.png);\n"
"border-radius:10px;")
        self.pushButtonOther.setObjectName("pushButtonOther")
        self.pushButtonAddNote = QtWidgets.QPushButton(self.widget)
        self.pushButtonAddNote.setGeometry(QtCore.QRect(50, 290, 271, 31))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(12)
        self.pushButtonAddNote.setFont(font)
        self.pushButtonAddNote.setStyleSheet("border-image: url(:/Images/Beige2.png);\n"
"border-radius:10px;")
        self.pushButtonAddNote.setObjectName("pushButtonAddNote")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 686, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelMenu.setText(_translate("MainWindow", "Menu"))
        self.pushButtonAddOpinion.setText(_translate("MainWindow", "Ajouter un Avis"))
        self.pushButtonViewOpinion.setText(_translate("MainWindow", "Consulter des Avis"))
        self.pushButtonViewRestaurants.setText(_translate("MainWindow", "Consulter les Restaurants"))
        self.pushButtonOther.setText(_translate("MainWindow", "Autres"))
        self.pushButtonAddNote.setText(_translate("MainWindow", "Ajouter une Note"))
from . import res_rc
