# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Other.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Other(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(686, 895)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-image: url(:/Images/DesignBgr.png);")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(150, 160, 391, 451))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        self.widget.setFont(font)
        self.widget.setStyleSheet("border-radius:50px;\n"
"border-image: url(:/Images/Beige1.png);")
        self.widget.setObjectName("widget")
        self.labelAutre = QtWidgets.QLabel(self.widget)
        self.labelAutre.setGeometry(QtCore.QRect(80, 10, 251, 51))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(20)
        self.labelAutre.setFont(font)
        self.labelAutre.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAutre.setObjectName("labelAutre")
        self.pushButtonAvisSup3 = QtWidgets.QPushButton(self.widget)
        self.pushButtonAvisSup3.setGeometry(QtCore.QRect(50, 90, 300, 31))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(12)
        self.pushButtonAvisSup3.setFont(font)
        self.pushButtonAvisSup3.setStyleSheet("border-image: url(:/Images/Beige2.png);\n"
"border-radius:10px;")
        self.pushButtonAvisSup3.setObjectName("pushButtonAvisSup3")
        self.pushButtonPlatPlusCher = QtWidgets.QPushButton(self.widget)
        self.pushButtonPlatPlusCher.setGeometry(QtCore.QRect(50, 140, 300, 31))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(12)
        self.pushButtonPlatPlusCher.setFont(font)
        self.pushButtonPlatPlusCher.setStyleSheet("border-image: url(:/Images/Beige2.png);\n"
"border-radius:10px;")
        self.pushButtonPlatPlusCher.setObjectName("pushButtonPlatPlusCher")
        self.pushButtonClientsMexicains = QtWidgets.QPushButton(self.widget)
        self.pushButtonClientsMexicains.setGeometry(QtCore.QRect(50, 190, 300, 31))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(12)
        self.pushButtonClientsMexicains.setFont(font)
        self.pushButtonClientsMexicains.setStyleSheet("border-image: url(:/Images/Beige2.png);\n"
"border-radius:10px;")
        self.pushButtonClientsMexicains.setObjectName("pushButtonClientsMexicains")
        self.pushButtonPlatsAsiatiques = QtWidgets.QPushButton(self.widget)
        self.pushButtonPlatsAsiatiques.setGeometry(QtCore.QRect(50, 240, 300, 31))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(12)
        self.pushButtonPlatsAsiatiques.setFont(font)
        self.pushButtonPlatsAsiatiques.setStyleSheet("border-image: url(:/Images/Beige2.png);\n"
"border-radius:10px;")
        self.pushButtonPlatsAsiatiques.setObjectName("pushButtonPlatsAsiatiques")
        self.pushButtonCodePostalPiresRestos = QtWidgets.QPushButton(self.widget)
        self.pushButtonCodePostalPiresRestos.setGeometry(QtCore.QRect(50, 290, 300, 31))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(12)
        self.pushButtonCodePostalPiresRestos.setFont(font)
        self.pushButtonCodePostalPiresRestos.setStyleSheet("border-image: url(:/Images/Beige2.png);\n"
"border-radius:10px;")
        self.pushButtonCodePostalPiresRestos.setObjectName("pushButtonCodePostalPiresRestos")
        self.pushButtonTypeNourritureParNote = QtWidgets.QPushButton(self.widget)
        self.pushButtonTypeNourritureParNote.setGeometry(QtCore.QRect(50, 340, 300, 31))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(12)
        self.pushButtonTypeNourritureParNote.setFont(font)
        self.pushButtonTypeNourritureParNote.setStyleSheet("border-image: url(:/Images/Beige2.png);\n"
"border-radius:10px;")
        self.pushButtonTypeNourritureParNote.setObjectName("pushButtonTypeNourritureParNote")
        self.buttonBoxOkRetour = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBoxOkRetour.setGeometry(QtCore.QRect(260, 580, 171, 16))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(12)
        self.buttonBoxOkRetour.setFont(font)
        self.buttonBoxOkRetour.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBoxOkRetour.setCenterButtons(True)
        self.buttonBoxOkRetour.setObjectName("buttonBoxOkRetour")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 686, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelAutre.setText(_translate("MainWindow", "Autres"))
        self.pushButtonAvisSup3.setText(_translate("MainWindow", "Restaurants avec un avis >= 3"))
        self.pushButtonPlatPlusCher.setText(_translate("MainWindow", "Restaurant avec plat le + cher"))
        self.pushButtonClientsMexicains.setText(_translate("MainWindow", "10 clients mageant le + mexicain"))
        self.pushButtonPlatsAsiatiques.setText(_translate("MainWindow", "Non-asiatique avec le + plats asiat"))
        self.pushButtonCodePostalPiresRestos.setText(_translate("MainWindow", "Code postal avec les - restaurants"))
        self.pushButtonTypeNourritureParNote.setText(_translate("MainWindow", "Type de nourriture le + present/note"))
from . import res_rc
