# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RestaurateurMenuWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RestaurateurMenu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(686, 900)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-image: url(:/Images/DesignBgr.png);")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(140, 160, 391, 451))
        self.widget.setStyleSheet("border-radius:50px;\n"
"border-image: url(:/Images/Beige1.png);")
        self.widget.setObjectName("widget")
        self.labelMenu = QtWidgets.QLabel(self.widget)
        self.labelMenu.setGeometry(QtCore.QRect(110, 10, 161, 51))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(20)
        self.labelMenu.setFont(font)
        self.labelMenu.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMenu.setObjectName("labelMenu")
        self.pushButtonAddResto = QtWidgets.QPushButton(self.widget)
        self.pushButtonAddResto.setGeometry(QtCore.QRect(50, 80, 291, 31))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(12)
        self.pushButtonAddResto.setFont(font)
        self.pushButtonAddResto.setStyleSheet("border-image: url(:/Images/Beige2.png);\n"
"border-radius:10px;")
        self.pushButtonAddResto.setObjectName("pushButtonAddResto")
        self.pushButtonEditResto = QtWidgets.QPushButton(self.widget)
        self.pushButtonEditResto.setGeometry(QtCore.QRect(50, 140, 291, 31))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(12)
        self.pushButtonEditResto.setFont(font)
        self.pushButtonEditResto.setStyleSheet("border-image: url(:/Images/Beige2.png);\n"
"border-radius:10px;")
        self.pushButtonEditResto.setObjectName("pushButtonEditResto")
        self.pushButtonAddMeals = QtWidgets.QPushButton(self.widget)
        self.pushButtonAddMeals.setGeometry(QtCore.QRect(50, 200, 291, 31))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(12)
        self.pushButtonAddMeals.setFont(font)
        self.pushButtonAddMeals.setStyleSheet("border-image: url(:/Images/Beige2.png);\n"
"border-radius:10px;")
        self.pushButtonAddMeals.setObjectName("pushButtonAddMeals")
        self.pushButtonCheckOpinions = QtWidgets.QPushButton(self.widget)
        self.pushButtonCheckOpinions.setGeometry(QtCore.QRect(50, 260, 291, 31))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(12)
        self.pushButtonCheckOpinions.setFont(font)
        self.pushButtonCheckOpinions.setStyleSheet("border-image: url(:/Images/Beige2.png);\n"
"border-radius:10px;")
        self.pushButtonCheckOpinions.setObjectName("pushButtonCheckOpinions")
        self.pushButtonStat = QtWidgets.QPushButton(self.widget)
        self.pushButtonStat.setGeometry(QtCore.QRect(50, 320, 291, 31))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(12)
        self.pushButtonStat.setFont(font)
        self.pushButtonStat.setStyleSheet("border-image: url(:/Images/Beige2.png);\n"
"border-radius:10px;")
        self.pushButtonStat.setObjectName("pushButtonStat")
        self.pushButtonOther = QtWidgets.QPushButton(self.widget)
        self.pushButtonOther.setGeometry(QtCore.QRect(50, 380, 291, 31))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(12)
        self.pushButtonOther.setFont(font)
        self.pushButtonOther.setStyleSheet("border-image: url(:/Images/Beige2.png);\n"
"border-radius:10px;")
        self.pushButtonOther.setObjectName("pushButtonOther")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 686, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelMenu.setText(_translate("MainWindow", "Menu"))
        self.pushButtonAddResto.setText(_translate("MainWindow", "Ajouter un Nouveau Restaurant"))
        self.pushButtonEditResto.setText(_translate("MainWindow", "Gerer ses Restaurants"))
        self.pushButtonAddMeals.setText(_translate("MainWindow", "Ajouter des Plats aux Menus"))
        self.pushButtonCheckOpinions.setText(_translate("MainWindow", "Consulter les Avis des Restaurants"))
        self.pushButtonStat.setText(_translate("MainWindow", "Statistiques"))
        self.pushButtonOther.setText(_translate("MainWindow", "Autres"))
from . import res_rc
