# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModoDeleteOpinion.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SupprimerAvisModo(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(686, 900)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-image: url(:/Images/DesignBgr.png);")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(150, 160, 391, 451))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        self.widget.setFont(font)
        self.widget.setStyleSheet("border-radius:50px;\n"
"border-image: url(:/Images/Beige1.png);")
        self.widget.setObjectName("widget")
        self.labelCheckOpinionModo = QtWidgets.QLabel(self.widget)
        self.labelCheckOpinionModo.setGeometry(QtCore.QRect(0, 0, 391, 31))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(20)
        self.labelCheckOpinionModo.setFont(font)
        self.labelCheckOpinionModo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCheckOpinionModo.setObjectName("labelCheckOpinionModo")
        self.pushButtonDelete = QtWidgets.QPushButton(self.widget)
        self.pushButtonDelete.setGeometry(QtCore.QRect(90, 410, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.pushButtonDelete.setFont(font)
        self.pushButtonDelete.setMouseTracking(True)
        self.pushButtonDelete.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonDelete.setAcceptDrops(False)
        self.pushButtonDelete.setStyleSheet("border-image: url(:/Images/Beige2.png);\n"
"border-radius:10px;\n"
"color: rgba(170, 0, 0, 250);")
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.textBrowserAvisASupprimer = QtWidgets.QTextBrowser(self.widget)
        self.textBrowserAvisASupprimer.setGeometry(QtCore.QRect(30, 40, 331, 171))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(12)
        self.textBrowserAvisASupprimer.setFont(font)
        self.textBrowserAvisASupprimer.setStyleSheet("border-image: url(:/Images/Beige2.png);\n"
"border-radius:10px;")
        self.textBrowserAvisASupprimer.setObjectName("textBrowserAvisASupprimer")
        self.plainTextEditJustificationSuppression = QtWidgets.QPlainTextEdit(self.widget)
        self.plainTextEditJustificationSuppression.setGeometry(QtCore.QRect(30, 220, 331, 151))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(12)
        self.plainTextEditJustificationSuppression.setFont(font)
        self.plainTextEditJustificationSuppression.setStyleSheet("border-image: url(:/Images/Beige2.png);\n"
"border-radius:10px;")
        self.plainTextEditJustificationSuppression.setObjectName("plainTextEditJustificationSuppression")
        self.pushButtonRetour = QtWidgets.QPushButton(self.widget)
        self.pushButtonRetour.setGeometry(QtCore.QRect(210, 410, 101, 31))
        self.pushButtonRetour.setMouseTracking(True)
        self.pushButtonRetour.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonRetour.setStyleSheet("border-image: url(:/Images/Beige2.png);\n"
"border-radius:10px;")
        self.pushButtonRetour.setObjectName("pushButtonRetour")
        self.labelError = QtWidgets.QLabel(self.widget)
        self.labelError.setGeometry(QtCore.QRect(-40, 380, 420, 20))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(10)
        self.labelError.setFont(font)
        self.labelError.setStyleSheet("color: rgb(255, 0, 0);")
        self.labelError.setText("")
        self.labelError.setAlignment(QtCore.Qt.AlignCenter)
        self.labelError.setObjectName("labelError")
        self.buttonBoxOkRetour = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBoxOkRetour.setGeometry(QtCore.QRect(450, 880, 171, 31))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(12)
        self.buttonBoxOkRetour.setFont(font)
        self.buttonBoxOkRetour.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBoxOkRetour.setCenterButtons(True)
        self.buttonBoxOkRetour.setObjectName("buttonBoxOkRetour")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 686, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelCheckOpinionModo.setText(_translate("MainWindow", "Supprimer un Avis par Modo"))
        self.pushButtonDelete.setText(_translate("MainWindow", "Supprimer l\'Avis"))
        self.plainTextEditJustificationSuppression.setPlainText(_translate("MainWindow", "Ecrivez la Justification de la Suppression de l\'Avis"))
        self.pushButtonRetour.setText(_translate("MainWindow", "Retour"))
from . import res_rc
